freebsd_instance:
  image_family: freebsd-13-0

freebsd_task:
  install_script:
    - pkg install -y perl5
    - perl -V
    - cpan -T App::cpanminus
    - perl '-MExtUtils::MakeMaker 6.68' -e '' || cpanm --quiet --notest ExtUtils::MakeMaker@6.68
    - perl '-MCPAN::Meta 2.112580' -e '' || cpanm --quiet --notest CPAN::Meta@2.112580
    - cpanm --quiet --notest --skip-satisfied --installdeps --with-configure --with-develop --with-recommends --with-suggests .

  build_script:
    - perl Makefile.PL
    - make

  test_script:
    - make test TEST_VERBOSE=1
